# Generated by Django 3.1.7 on 2021-03-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charity_donation", "0003_donation_is_takken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donation",
            old_name="is_takken",
            new_name="is_taken",
        ),
    ]
