# Generated by Django 3.1.7 on 2021-04-03 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity_donation", "0011_auto_20210403_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="address",
            field=models.CharField(
                max_length=60,
                validators=[
                    django.core.validators.ProhibitNullCharactersValidator(
                        message="Pole jest wymagane"
                    )
                ],
            ),
        ),
    ]
