# Generated by Django 3.1.7 on 2021-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity_donation", "0012_auto_20210403_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="address",
            field=models.CharField(max_length=60),
        ),
    ]
