# Generated by Django 3.1.7 on 2021-04-03 14:21

import charity_donation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity_donation", "0013_auto_20210403_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="pick_up_date",
            field=models.DateField(validators=[charity_donation.models.validate_date]),
        ),
    ]
